apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector.morven.me
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU5MYStUdElOMVRuM0tQMVYxbG8wamt3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pUYzBNMlpsTVRRdE5UWmtNaTAwWkRFMUxXSTRZVFV0TXpRd01qaGlZbVZtTmpobApNQ0FYRFRJeE1EZ3dNekV5TXpJd01Wb1lEekl3TlRFd056STNNVE16TWpBeFdqQXZNUzB3S3dZRFZRUURFeVJsCk56UXpabVV4TkMwMU5tUXlMVFJrTVRVdFlqaGhOUzB6TkRBeU9HSmlaV1kyT0dVd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FET081L1MzK3hSVUdMQkNOVVF5WlRXT1VpeXdaQjYzQks0cm5VeQphamhJcjFtMlIrSWw1ZlExYVE3MlJOekg2MWNqQWZJdUdjdnVSdnJEU3dBMEhhdGN1WTNtUDF3OUMyRXQ4MnZRCnZKTlZobFVpOTFtdEpoYTZMcnBPN1FUUWN0TUhHWUpwWUlJUDlyQU95cmNFYmlvcGcyVWR2OXoxTlJXVTA2NisKVmhQS1c1ZjJDQmJVckR5dXE0OFZ1MVNqN1FtcVRWdkVjaHhlRlMzeGF4UTJqbjNOZmIvVXBqb2Z5ODduQkhvcwpRTEF0VUQ3WlNHbjltZjN1dHBqVjgyK240Zncyei9tdHhQUW03RUJFaTF6YXFIRDJzYVU3NkRlT2JGOG85RjBGClYrUWtvRytPbWZkU1NTSHZObndTN01PbEs0TXZiM3EzZ3lxNTVuV1BjTFhFclRZazk0TmdOQktGcW9nOTNGMzQKT0dsM3BxVE5iNlpwUlJjU0ZNWkNURGlGZkUxeXZqdVpvMUZBTFo2aGQxUDZJRjlHWnJaU2g3MU9lamNVcXJkSQpVcTErVnUreUpUODV0Y2k4dDdyeWNGYjRXZzk5OVkwUkdxQktUYVlsZTYrV0NEUVdwVWtMRTNRM3dFTVhrbU5FCm54MG83K3pQdW1DcXlVblI1Uk9kRUxqdnJ2Y0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTzdWQlQ0UFhHUmd1S0ppcmVRM1RFZ2phaVMyTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQjdNYmNxTm9ZZnVwOWxjVU11OFY2aVoya1gwUEw0RzVoTnJJeUhSNzA4Ci8xSjZvS0RRZldIWHpkU3gwMndpQnZKcmpxZ3ZWYUx5OFR0Q3VoN2c0K0N3VWs1aEI3YjlUckNxTXQ5K3RxcHMKZDk1WFR5T1I3bmM4YjZqN3JDQkdkUFgvN3EwN0hNcWcyY0YyMi8xY3VBVDVvaDAvWGVDUEJCN3pJNDBoOEJ5bApJcjZOcmZxYm40MUREeXpzN1ZGaDJoTzUwN3laR0M1L0w0NkhRZlBPN2d3OEVjZVp3Wk9HaVRtZm5UNjRONXJCCkkvTmhmOHhnVjdYNHZYa0NUTTVXYU1OT0ltMGdIYmdQVlBhaUNFc3BCTjJaMlRrZEZyU3dYTDV1YnlzcFpOSXcKNi94WjlvcE9vL04yZmhxNHVtRHcyeEIxb0Vsakd5YWJFaCszSi95QStvN0syUGxNQTRIdkxWdnVPODZNdG8vdAozOGdpRmZocERRa2c2SW9QWkFLcis0SGtkU0U1eVY3amhxUm9DbGg5SG1QVUdPUTRWM0dsUXRDdXlDMUVJMG1kCkJjemZldHJSVUZOQXJqL2RCTW1HYjBoRHdvRnIxRTJBYklIZFpuaTk1M044SEJXTUZTcjUvWVowQU9iVk4ybjMKVEhjZ1ZqQWlXZ0k0ZzBLN0RDd2tCZFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
